const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Platform: 0},
	{Sprite4: 0},
	{Solid: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{profil: 0},
	{materi: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Touch: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{exitgame: 0},
	{Text: 0},
	{Video: 0},
	{video_profil: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{TentuIniAdalahMateriLengkapTentangSepakBolaMulaiDariSejarahAturanDasarPosisiPemainTeknikHinggaKompetisiTerkenalnyaLengkapDenganContohcontohYangMudahDipahamiMateri: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite12: 0},
	{DragDrop: 0},
	{Text2: 0},
	{Text3: 0},
	{Bullet: 0},
	{Sine: 0},
	{Sine2: 0},
	{bubble: 0},
	{Particles: 0},
	{scorebubble: 0},
	{Text4: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	profil: class extends self.ISpriteInstance {},
	materi: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	exitgame: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	video_profil: class extends self.IWorldInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	TentuIniAdalahMateriLengkapTentangSepakBolaMulaiDariSejarahAturanDasarPosisiPemainTeknikHinggaKompetisiTerkenalnyaLengkapDenganContohcontohYangMudahDipahamiMateri: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	bubble: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	scorebubble: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {}
}